services:
  nebula:
    image: ghcr.io/nebulaservices/nebula:latest
    container_name: nebula
    restart: unless-stopped
    ports:
      # HOST:CONTAINER (DO NOT CHANGE THE CONTAINER PORT, UNLESS EDITED IN THE config.toml FILE)
      - 8080:8080
    volumes:
      - ./config.toml:/app/config.toml 
# Uncomment the the below stuff to use POSTGRES!
#  db:
#    image: postgres
#    restart: unless-stopped
#    environment:
#      POSTGRES_PASSWORD: password #CHANGE THIS
#      POSTGRES_USER: username
#      POSTGRES_DB: db
#    volumes:
#      - ./db:/var/lib/postgresql/data
